{% set name = "aiofiles" %}
{% set version = "23.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiofiles-{{ version }}.tar.gz
  sha256: 84ec2218d8419404abcb9f0c02df3f34c6e0a68ed41072acfb1cef5cbc29051a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7

test:
  imports:
    - aiofiles

about:
  home: https://github.com/Tinche/aiofiles
  summary: File support for asyncio
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  dev_url: https://github.com/Tinche/aiofiles
  doc_url: https://github.com/Tinche/aiofiles/blob/main/README.md

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for chainlit
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - xylar
    - kszucs
    - carlodri
