{% set name = "aiofiles" %}
{% set version = "24.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22a075c9e5a3810f0c2e48f3008c94d68c65d763b9b03857924c99e57355166c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - aiofiles
  commands:
    - pip check
    - pytest -v --asyncio-mode=auto tests
  requires:
    - pip
    - pytest >=8.2.2
    - pytest-asyncio >=0.23.7

about:
  home: https://github.com/Tinche/aiofiles
  summary: File support for asyncio
  description: syaiofiles is an Apache2 licensed library, written in Python, for handling local disk files in asyncio applications.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/Tinche/aiofiles
  doc_url: https://github.com/Tinche/aiofiles/blob/main/README.md

extra:
  recipe-maintainers:
    - kszucs
    - carlodri
