{% set name = "aiofiles" %}
{% set version = "22.1.0" %}
{% set sha256 = "9107f1ca0b2a5553987a94a3c9959fe5b491fdf731389aa5b7b1bd0733e32de6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true # [py<37]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.4.0
    - wheel
  run:
    - python

test:
  imports:
    - aiofiles
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Tinche/aiofiles
  summary: File support for asyncio
  description: syaiofiles is an Apache2 licensed library, written in Python, for handling local disk files in asyncio applications.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/Tinche/aiofiles
  doc_url: https://github.com/Tinche/aiofiles/blob/main/README.rst

extra:
  recipe-maintainers:
    - kszucs
    - carlodri
