travis:
  secure:
    BINSTAR_TOKEN: zmGS0InwNkb2KTt9E4iGfYrnIAXUsWk20i5H2BzD0GmFBhz8tzyYPYK3yn3VyLIBFFWEYwdu9LkJZ6NJ64v3jhrF9j/Sy2WDospfymhiuMcNIjd9fv1NUrxpo+m5NGlOVUOEOnSDkjXB9x9xdWU/7oNQNtgfFE/T3PaqjrpTuFQaQlwqEX7MoCcgWPK+NwFfQt4s5Ib+hDQ28H8teOC9klIGi5eSyPp6F4wEKVzQ35YZc0YKM7roofhsluHs/TFACxTGsRKWnTIYJex4Tx36aVWIDIwqqo3t0s+hdtK4uKlRtOIZNr6tc6SSX/1VlFG1Nt5SI+kyJMHHVwOAQTReVV+iMvU3ayqmYJbyO+JuTgeAoFkECnTsjP8j/FKOu8XghgAPzWrtK/4gS2uROjGf5hwGG+6XV/s2iJe2Nxs/ZOANrlOGKLBUGSGyrjcTbqFWEpoKSiZwiX4c3RWP6uaO2mrh7IFirbRQVHTJMCBoEcPBj+LzAsfDsdlsSpvh22OlSNp7sPR796iWne5LjVYT5z7F01ygLc73fjxWgkCxedGCKAe1/z2MQgJJqcdYFaTFNlGVh8PFLsnnJDilzHVAKllzqywUUgyaL91/7HjW0uTM+bEfDdLgs9Z8+OKyKOxBdg2hgs04eaOXjPqtToJQGqrKyMneCv7IR6lyGARyevA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
